---@alias not_crafting.class.recipe.ingredient { item?: int, items?: int[], count?: int, tag?: str }
---@alias not_crafting.class.recipe.result { id: int, count?: int };

---@class not_crafting.class.recipe
---@field path str
---@field type str
---@field category str
---@field group? str
---@field cookingtime int
---@field experience number
---@field key table<str, not_crafting.class.recipe.ingredient>
---@field ingredients not_crafting.class.recipe.ingredient[]
---@field ingredient not_crafting.class.recipe.ingredient
---@field pattern str[]
---@field result not_crafting.class.recipe.result
